---
title: "05_operon_enrichment"
output: html_document
---

# Operon enrichment

## Operons investigation

### Generating operon names
```{r operon_names, warning=FALSE, comments="", message=FALSE}
operon_names <- bsg_annotation %>%
  filter(!is.na(operon_id)) %>%
  group_by(operon_id) %>%
  arrange(
    if_else(strand == "+", start, -start),
    .by_group = TRUE
  ) %>%
  summarise(
    operon_name = {
      g <- gene[!is.na(gene) & gene != ""]
      g <- g[!duplicated(g)]
      n <- min(3, length(g))
      
      if (length(g) == 0) {
        NA_character_
      } else {
        paste0(
          paste(g[1:n], collapse = "-"),
          ifelse(length(g) > 3, "-etc", "")
        )
      }
    },
    .groups = "drop"
  )


operon_mapping <- complete_gene_annotation %>%
  left_join(operon_names, by = "operon_id")

complete_gene_annotation <- complete_gene_annotation %>%
  left_join(operon_names, by = "operon_id")
```



### Goethite

```{r operon_goe, warning=FALSE, comments="", message=FALSE}

############ Goethite 3 h
# Add operon info to DE results
res_operon <- res_3h_G %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon$operon_id))  # How many DE genes are in operons

operon_summary <- res_operon %>%
  filter(adj.P.Val < 0.05) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons <- res_operon %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))

top_operons <- head(de_operons$operon_id, 10)

top_operon_genes <- res_operon %>%
  filter(adj.P.Val < 0.05, operon_id %in% top_operons) %>%
  mutate(direction = ifelse(logFC > 0, "up", "down"))

# Aggregate up/down counts
top_operon_summary <- top_operon_genes %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  mutate(n_DE = ifelse(direction == "down", -n_DE, n_DE))  # negative for down

ggplot(top_operon_summary, aes(x = reorder(operon_name, n_DE), y = n_DE, fill = direction)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(values = c("up" = "red", "down" = "blue")) +
  labs(x = "Operon", y = "Number of DE genes", title = "Top 10 operons with most DE genes - Goethite 3h") +
  theme_minimal()

############# Goethite 24 h
# Add operon info to DE results
res_operon <- res_24h_G %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon$operon_id))  # How many DE genes are in operons

operon_summary <- res_operon %>%
  filter(adj.P.Val < 0.05) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons <- res_operon %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))

top_operons <- head(de_operons$operon_id, 10)

top_operon_genes <- res_operon %>%
  filter(adj.P.Val < 0.05, operon_id %in% top_operons) %>%
  mutate(direction = ifelse(logFC > 0, "up", "down"))

# Aggregate up/down counts
top_operon_summary <- top_operon_genes %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  mutate(n_DE = ifelse(direction == "down", -n_DE, n_DE))  # negative for down

ggplot(top_operon_summary, aes(x = reorder(operon_name, n_DE), y = n_DE, fill = direction)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(values = c("up" = "red", "down" = "blue")) +
  labs(x = "Operon", y = "Number of DE genes", title = "Top 10 operons with most DE genes - Goethite 24h") +
  theme_minimal()
```

### Hematite

```{r operon_hem, warning=FALSE, comments="", message=FALSE}
############ Hematite 3 h
# Add operon info to DE results
res_operon <- res_3h_H %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon$operon_id))  # How many DE genes are in operons

operon_summary <- res_operon %>%
  filter(adj.P.Val < 0.05) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons <- res_operon %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))

top_operons <- head(de_operons$operon_id, 10)

top_operon_genes <- res_operon %>%
  filter(adj.P.Val < 0.05, operon_id %in% top_operons) %>%
  mutate(direction = ifelse(logFC > 0, "up", "down"))

# Aggregate up/down counts
top_operon_summary <- top_operon_genes %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  mutate(n_DE = ifelse(direction == "down", -n_DE, n_DE))  # negative for down

ggplot(top_operon_summary, aes(x = reorder(operon_name, n_DE), y = n_DE, fill = direction)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(values = c("up" = "red", "down" = "blue")) +
  labs(x = "Operon", y = "Number of DE genes", title = "Top 10 operons with most DE genes - Hemaite 3h") +
  theme_minimal()

############# Hematite 24 h
# Add operon info to DE results
res_operon <- res_24h_H %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon$operon_id))  # How many DE genes are in operons

operon_summary <- res_operon %>%
  filter(adj.P.Val < 0.05) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons <- res_operon %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))

top_operons <- head(de_operons$operon_id, 10)

top_operon_genes <- res_operon %>%
  filter(adj.P.Val < 0.05, operon_id %in% top_operons) %>%
  mutate(direction = ifelse(logFC > 0, "up", "down"))

# Aggregate up/down counts
top_operon_summary <- top_operon_genes %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  mutate(n_DE = ifelse(direction == "down", -n_DE, n_DE))  # negative for down

ggplot(top_operon_summary, aes(x = reorder(operon_name, n_DE), y = n_DE, fill = direction)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(values = c("up" = "red", "down" = "blue")) +
  labs(x = "Operon", y = "Number of DE genes", title = "Top 10 operons with most DE genes - Hematite 24h") +
  theme_minimal()
```

### Mica

```{r operon_mic, warning=FALSE, comments="", message=FALSE}
############ Mica 3 h
# Add operon info to DE results
res_operon <- res_3h_M %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon$operon_id))  # How many DE genes are in operons

operon_summary <- res_operon %>%
  filter(adj.P.Val < 0.05) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons <- res_operon %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))

top_operons <- head(de_operons$operon_id, 10)

top_operon_genes <- res_operon %>%
  filter(adj.P.Val < 0.05, operon_id %in% top_operons) %>%
  mutate(direction = ifelse(logFC > 0, "up", "down"))

# Aggregate up/down counts
top_operon_summary <- top_operon_genes %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  mutate(n_DE = ifelse(direction == "down", -n_DE, n_DE))  # negative for down

ggplot(top_operon_summary, aes(x = reorder(operon_name, n_DE), y = n_DE, fill = direction)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(values = c("up" = "red", "down" = "blue")) +
  labs(x = "Operon", y = "Number of DE genes", title = "Top 10 operons with most DE genes - Mica 3h") +
  theme_minimal()

############# Mica 24 h
# Add operon info to DE results
res_operon <- res_24h_M %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon$operon_id))  # How many DE genes are in operons

operon_summary <- res_operon %>%
  filter(adj.P.Val < 0.05) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons <- res_operon %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))

top_operons <- head(de_operons$operon_id, 10)

top_operon_genes <- res_operon %>%
  filter(adj.P.Val < 0.05, operon_id %in% top_operons) %>%
  mutate(direction = ifelse(logFC > 0, "up", "down"))

# Aggregate up/down counts
top_operon_summary <- top_operon_genes %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  mutate(n_DE = ifelse(direction == "down", -n_DE, n_DE))  # negative for down

ggplot(top_operon_summary, aes(x = reorder(operon_name, n_DE), y = n_DE, fill = direction)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(values = c("up" = "red", "down" = "blue")) +
  labs(x = "Operon", y = "Number of DE genes", title = "Top 10 operons with most DE genes - Mica 24h") +
  theme_minimal()
```


### Overlaps 3h


```{r ovelaps_3h, warning=FALSE, comments="", message=FALSE}
get_directional_genes <- function(res, padj_cutoff = 0.05, lfc_cutoff = 0) {
  res_tbl <- res %>%
    rownames_to_column("ID_prodigal")
  
  up_genes <- res_tbl %>%
    filter(adj.P.Val < padj_cutoff, logFC > lfc_cutoff) %>%
    pull(ID_prodigal)
  
  down_genes <- res_tbl %>%
    filter(adj.P.Val < padj_cutoff, logFC < -lfc_cutoff) %>%
    pull(ID_prodigal)
  
  list(
    up = unique(up_genes),
    down = unique(down_genes)
  )
}

dir_G <- get_directional_genes(res_3h_G)
dir_H <- get_directional_genes(res_3h_H)
dir_M <- get_directional_genes(res_3h_M)

up_list <- list(
  G = dir_G$up,
  H = dir_H$up,
  M = dir_M$up
)

down_list <- list(
  G = dir_G$down,
  H = dir_H$down,
  M = dir_M$down
)


up_input <- fromList(up_list)
down_input <- fromList(down_list)

upset(
  up_input,
  sets = c("G", "H", "M"),
  order.by = "freq",
  main.bar.color = "firebrick",
  sets.bar.color = c("#E1AD01","#800020", "#B8B8B8"),
  mainbar.y.label = "Shared upregulated genes",
  sets.x.label = "Upregulated genes per condition"
)

upset(
  down_input,
  sets = c("G", "H", "M"),
  order.by = "freq",
  main.bar.color = "navy",
  sets.bar.color = c("#E1AD01","#800020", "#B8B8B8"),
  mainbar.y.label = "Shared downregulated genes",
  sets.x.label = "Downregulated genes per condition"
)


annotate_with_operons <- function(res, complete_gene_annotation_bsg, condition_name) {
  res %>%
    rownames_to_column("ID_prodigal") %>%
    left_join(
      complete_gene_annotation_bsg %>%
        select(ID_prodigal, gene, locus_tag, operon_id, operon_name),
      by = "ID_prodigal"
    ) %>%
    mutate(condition = condition_name)
}

res_G_operon <- annotate_with_operons(res_3h_G, complete_gene_annotation, "G")
res_H_operon <- annotate_with_operons(res_3h_H, complete_gene_annotation, "H")
res_M_operon <- annotate_with_operons(res_3h_M, complete_gene_annotation, "M")

all_operon_res <- bind_rows(res_G_operon, res_H_operon, res_M_operon) %>%
  mutate(
    direction = case_when(
      adj.P.Val < 0.05 & logFC > 0 ~ "up",
      adj.P.Val < 0.05 & logFC < 0 ~ "down",
      TRUE ~ "not_DE"
    )
  )

operon_condition_summary <- all_operon_res %>%
  filter(!is.na(operon_id)) %>%
  group_by(operon_id, operon_name, condition) %>%
  summarise(
    n_genes = n(),
    n_up = sum(direction == "up"),
    n_down = sum(direction == "down"),
    mean_logFC = mean(logFC, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    operon_state = case_when(
      n_up >= 2 & n_down == 0   ~ "up",
      n_down >= 2 & n_up == 0   ~ "down",
      TRUE ~ "mixed_or_notDE"
    )
  )

operon_wide <- operon_condition_summary %>%
  select(operon_id, operon_name, condition, operon_state, n_up, n_down, mean_logFC) %>%
  pivot_wider(
    names_from = condition,
    values_from = c(operon_state, n_up, n_down, mean_logFC)
  )

operons_up_all <- operon_wide %>%
  filter(
    operon_state_G == "up",
    operon_state_H == "up",
    operon_state_M == "up"
  )

operons_down_all <- operon_wide %>%
  filter(
    operon_state_G == "down",
    operon_state_H == "down",
    operon_state_M == "down"
  )


heatmap_df <- operon_condition_summary %>%
  filter(operon_id %in% operons_up_all$operon_id | operon_id %in% operons_down_all$operon_id)

ggplot(heatmap_df, aes(x = condition, y = operon_name, fill = mean_logFC)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal() +
  labs(x = "Condition", y = "Operon", fill = "Mean logFC")



operon_condition_summary <- all_operon_res %>%
  filter(!is.na(operon_id)) %>%
  group_by(operon_id, operon_name, condition) %>%
  summarise(
    n_genes = n(),
    n_up = sum(direction == "up"),
    n_down = sum(direction == "down"),
    n_DE = sum(direction %in% c("up", "down")),
    mean_logFC = mean(logFC, na.rm = TRUE),
    .groups = "drop"
  )

top_variable_operons <- operon_condition_summary %>%
  group_by(operon_id, operon_name) %>%
  summarise(
    logFC_range = max(mean_logFC, na.rm = TRUE) - min(mean_logFC, na.rm = TRUE),
    has_pos = any(mean_logFC > 0, na.rm = TRUE),
    has_neg = any(mean_logFC < 0, na.rm = TRUE),
    n_conditions_DE = sum(n_DE > 0),
    .groups = "drop"
  ) %>%
  filter(n_conditions_DE >= 2, has_pos, has_neg) %>%
  arrange(desc(logFC_range)) %>%
  slice_head(n = 20)

heatmap_df_top <- operon_condition_summary %>%
  semi_join(top_variable_operons, by = c("operon_id", "operon_name"))

operon_order <- heatmap_df_top %>%
  select(operon_id, operon_name, condition, mean_logFC) %>%
  pivot_wider(names_from = condition, values_from = mean_logFC) %>%
  arrange(G, H, M) %>%
  pull(operon_name)

heatmap_df_top <- heatmap_df_top %>%
  mutate(operon_name = factor(operon_name, levels = operon_order))

ggplot(heatmap_df_top, aes(x = condition, y = operon_name, fill = mean_logFC)) +
  geom_tile(color = "grey85") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal() +
  labs(
    x = "Condition",
    y = "Operon",
    fill = "Mean logFC",
    title = "Top variable operons across conditions"
  )

```

### Overlap 24 h

```{r overlaps_24h, warning=FALSE, comments="", message=FALSE}

dir_G <- get_directional_genes(res_24h_G)
dir_H <- get_directional_genes(res_24h_H)
dir_M <- get_directional_genes(res_24h_M)

up_list <- list(
  G = dir_G$up,
  H = dir_H$up,
  M = dir_M$up
)

down_list <- list(
  G = dir_G$down,
  H = dir_H$down,
  M = dir_M$down
)


up_input <- fromList(up_list)
down_input <- fromList(down_list)

upset(
  up_input,
  sets = c("G", "H", "M"),
  order.by = "freq",
  main.bar.color = "firebrick",
  sets.bar.color = c("#E1AD01","#800020", "#B8B8B8"),
  mainbar.y.label = "Shared upregulated genes",
  sets.x.label = "Upregulated genes per condition"
)

upset(
  down_input,
  sets = c("G", "H", "M"),
  order.by = "freq",
  main.bar.color = "navy",
  sets.bar.color = c("#E1AD01","#800020", "#B8B8B8"),
  mainbar.y.label = "Shared downregulated genes",
  sets.x.label = "Downregulated genes per condition"
)



res_G_operon <- annotate_with_operons(res_24h_G, complete_gene_annotation, "G")
res_H_operon <- annotate_with_operons(res_24h_H, complete_gene_annotation, "H")
res_M_operon <- annotate_with_operons(res_24h_M, complete_gene_annotation, "M")

all_operon_res <- bind_rows(res_G_operon, res_H_operon, res_M_operon) %>%
  mutate(
    direction = case_when(
      adj.P.Val < 0.05 & logFC > 0 ~ "up",
      adj.P.Val < 0.05 & logFC < 0 ~ "down",
      TRUE ~ "not_DE"
    )
  )

operon_condition_summary <- all_operon_res %>%
  filter(!is.na(operon_id)) %>%
  group_by(operon_id, operon_name, condition) %>%
  summarise(
    n_genes = n(),
    n_up = sum(direction == "up"),
    n_down = sum(direction == "down"),
    mean_logFC = mean(logFC, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    operon_state = case_when(
      n_up >= 2 & n_down == 0   ~ "up",
      n_down >= 2 & n_up == 0   ~ "down",
      TRUE ~ "mixed_or_notDE"
    )
  )

operon_wide <- operon_condition_summary %>%
  select(operon_id, operon_name, condition, operon_state, n_up, n_down, mean_logFC) %>%
  pivot_wider(
    names_from = condition,
    values_from = c(operon_state, n_up, n_down, mean_logFC)
  )

operons_up_all <- operon_wide %>%
  filter(
    operon_state_G == "up",
    operon_state_H == "up",
    operon_state_M == "up"
  )

operons_down_all <- operon_wide %>%
  filter(
    operon_state_G == "down",
    operon_state_H == "down",
    operon_state_M == "down"
  )


heatmap_df <- operon_condition_summary %>%
  filter(operon_id %in% operons_up_all$operon_id | operon_id %in% operons_down_all$operon_id)

ggplot(heatmap_df, aes(x = condition, y = operon_name, fill = mean_logFC)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal() +
  labs(x = "Condition", y = "Operon", fill = "Mean logFC")



operon_condition_summary <- all_operon_res %>%
  filter(!is.na(operon_id)) %>%
  group_by(operon_id, operon_name, condition) %>%
  summarise(
    n_genes = n(),
    n_up = sum(direction == "up"),
    n_down = sum(direction == "down"),
    n_DE = sum(direction %in% c("up", "down")),
    mean_logFC = mean(logFC, na.rm = TRUE),
    .groups = "drop"
  )

top_variable_operons <- operon_condition_summary %>%
  group_by(operon_id, operon_name) %>%
  summarise(
    logFC_range = max(mean_logFC, na.rm = TRUE) - min(mean_logFC, na.rm = TRUE),
    has_pos = any(mean_logFC > 0, na.rm = TRUE),
    has_neg = any(mean_logFC < 0, na.rm = TRUE),
    n_conditions_DE = sum(n_DE > 0),
    .groups = "drop"
  ) %>%
  filter(n_conditions_DE >= 2, has_pos, has_neg) %>%
  arrange(desc(logFC_range)) %>%
  slice_head(n = 20)

heatmap_df_top <- operon_condition_summary %>%
  semi_join(top_variable_operons, by = c("operon_id", "operon_name"))

operon_order <- heatmap_df_top %>%
  select(operon_id, operon_name, condition, mean_logFC) %>%
  pivot_wider(names_from = condition, values_from = mean_logFC) %>%
  arrange(G, H, M) %>%
  pull(operon_name)

heatmap_df_top <- heatmap_df_top %>%
  mutate(operon_name = factor(operon_name, levels = operon_order))

ggplot(heatmap_df_top, aes(x = condition, y = operon_name, fill = mean_logFC)) +
  geom_tile(color = "grey85") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal() +
  labs(
    x = "Condition",
    y = "Operon",
    fill = "Mean logFC",
    title = "Top variable operons across conditions"
  )
```

## Heatmaps per functional category


```{r operons_category_heatmap, warning=FALSE, comments="", message=FALSE}
res_3h_G_de <- res_3h_G %>%
  filter(adj.P.Val < 0.05)

res_3h_H_de <- res_3h_H %>%
  filter(adj.P.Val < 0.05)

res_3h_M_de <- res_3h_M %>%
  filter(adj.P.Val < 0.05)

res_24h_G_de <- res_24h_G %>%
  filter(adj.P.Val < 0.05)

res_24h_H_de <- res_24h_H %>%
  filter(adj.P.Val < 0.05)

res_24h_M_de <- res_24h_M %>%
  filter(adj.P.Val < 0.05)

annotate_operons <- function(res_df) {
  res_df %>%
    rownames_to_column("ID_prodigal") %>%
    left_join(complete_gene_annotation, by = "ID_prodigal") %>%
    filter(!is.na(operon_id))
}

summarise_operons <- function(df, condition_name) {
  df %>%
    group_by(operon_id, operon_name) %>%
    summarise(
      mean_logFC = mean(logFC, na.rm = TRUE),
      n_genes = n(),
      n_up = sum(logFC > 0),
      n_down = sum(logFC < 0),
      direction = case_when(
        n_up > 0 & n_down == 0 ~ "up",
        n_down > 0 & n_up == 0 ~ "down",
        n_up > 0 & n_down > 0 ~ "mixed",
        TRUE ~ "none"
      ),
      .groups = "drop"
    ) %>%
    mutate(condition = condition_name)
}

operon_all <- bind_rows(
  summarise_operons(annotate_operons(res_3h_G_de), "3h_goethite"),
  summarise_operons(annotate_operons(res_3h_H_de), "3h_hematite"),
  summarise_operons(annotate_operons(res_3h_M_de), "3h_mica"),
  summarise_operons(annotate_operons(res_24h_G_de), "24h_goethite"),
  summarise_operons(annotate_operons(res_24h_H_de), "24h_hematite"),
  summarise_operons(annotate_operons(res_24h_M_de), "24h_mica")
)

selected_operons <- read_csv("data/Operons_selection.csv") %>%
  mutate(file_order = row_number()) %>%
  dplyr::rename(operon_name = Operon_name)

condition_order <- c(
    "3h_goethite",
    "3h_hematite",
    "3h_mica",
    "24h_goethite",
    "24h_hematite",
    "24h_mica"
  )

operon_order <- selected_operons$Operon_name

heatmap_df <- operon_all %>%
  filter(operon_name %in% selected_operons$operon_name)


heatmap_df_cat <- heatmap_df %>%
  inner_join(
    selected_operons %>% select(operon_name, Category, file_order),
    by = "operon_name"
  ) %>%
  mutate(
    condition = factor(condition, levels = condition_order),
    mean_logFC = ifelse(is.na(mean_logFC), 0, mean_logFC)
  )

plot_category_heatmap <- function(df, category_name) {
  df_cat <- df %>%
    filter(Category == category_name) %>%
    arrange(file_order) %>%
    mutate(
      operon_name = factor(operon_name, levels = rev(unique(operon_name)))
    )
  
  ggplot(df_cat, aes(x = condition, y = operon_name, fill = mean_logFC)) +
    geom_tile(color = "grey85") +
    scale_fill_gradient2(
      low = "blue",
      mid = "white",
      high = "red",
      midpoint = 0
    ) +
    theme_minimal() +
    labs(
      title = category_name,
      x = NULL,
      y = NULL,
      fill = "Mean logFC"
    )
}

category_names <- unique(selected_operons$Category)

plots_by_category <- lapply(category_names, function(cat) {
  plot_category_heatmap(heatmap_df_cat, cat)
})

names(plots_by_category) <- category_names

for (name in names(plots_by_category)) {
  print(plots_by_category[[name]] + ggtitle(name))
}
```



```{r markers_category_heatmap, warning=FALSE, comments="", message=FALSE}

marker_genes <- read_csv("data/Markers_selection.csv") %>%
  mutate(file_order = row_number()) %>%
  dplyr::rename(gene = Marker_name)


make_gene_table <- function(res, condition_name, annotation_df) {
  res %>%
    tibble::rownames_to_column("ID_prodigal") %>%
    left_join(
      annotation_df %>% dplyr::select(ID_prodigal, gene),
      by = "ID_prodigal"
    ) %>%
    mutate(
      condition = condition_name,
      logFC_plot = ifelse(adj.P.Val < 0.05, logFC, 0) # logFC_plot = logFC if I want all genes, not just DE
    ) %>%
    dplyr::select(ID_prodigal, gene, condition, logFC, adj.P.Val, logFC_plot)
}

gene_heatmap_df <- bind_rows(
  make_gene_table(res_3h_G,  "3h_goethite",  complete_gene_annotation),
  make_gene_table(res_3h_H,  "3h_hematite",  complete_gene_annotation),
  make_gene_table(res_3h_M,  "3h_mica",      complete_gene_annotation),
  make_gene_table(res_24h_G, "24h_goethite", complete_gene_annotation),
  make_gene_table(res_24h_H, "24h_hematite", complete_gene_annotation),
  make_gene_table(res_24h_M, "24h_mica",     complete_gene_annotation)
)

condition_order <- c(
  "3h_goethite",
  "3h_hematite",
  "3h_mica",
  "24h_goethite",
  "24h_hematite",
  "24h_mica"
)

gene_heatmap_df_cat <- gene_heatmap_df %>%
  inner_join(
    marker_genes %>% dplyr::select(gene, Category, file_order),
    by = "gene"
  ) %>%
  mutate(
    condition = factor(condition, levels = condition_order)
  )


plot_gene_category_heatmap <- function(df, category_name) {
  df_cat <- df %>%
    filter(Category == category_name) %>%
    arrange(file_order) %>%
    mutate(
      gene = factor(gene, levels = rev(unique(gene)))
    )
  
  ggplot(df_cat, aes(x = condition, y = gene, fill = logFC_plot)) +
    geom_tile(color = "grey85") +
    scale_fill_gradient2(
      low = "blue",
      mid = "white",
      high = "red",
      midpoint = 0
    ) +
    theme_minimal() +
    labs(
      title = category_name,
      x = NULL,
      y = NULL,
      fill = "logFC"
    )
}

gene_category_names <- unique(marker_genes$Category)

gene_plots_by_category <- lapply(gene_category_names, function(cat) {
  plot_gene_category_heatmap(gene_heatmap_df_cat, cat)
})

names(gene_plots_by_category) <- gene_category_names


for (name in names(gene_plots_by_category)) {
  print(gene_plots_by_category[[name]] + ggtitle(name))
}
```





## Investigating specific genes and operons - UNDER CONSTRUCTION


```{r specific_operon_3h, warning=FALSE, comments="", message=FALSE}

### Goethite
# Add operon info to DE results
res_operon_3h_G <- res_3h_G %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon_3h_G$operon_id))  # How many DE genes are in operons

operon_summary_3h_G <- res_operon_3h_G %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons_3h_G <- res_operon_3h_G %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))

### Hematite
# Add operon info to DE results
res_operon_3h_H <- res_3h_H %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon_3h_H$operon_id))  # How many DE genes are in operons

operon_summary_3h_H <- res_operon_3h_H %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons_3h_H <- res_operon_3h_H %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))


### Mica
# Add operon info to DE results
res_operon_3h_M <- res_3h_M %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon_3h_M$operon_id))  # How many DE genes are in operons

operon_summary_3h_M <- res_operon_3h_M %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons_3h_M <- res_operon_3h_M %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))
```
```{r specific_operon_24h, warning=FALSE, comments="", message=FALSE}
### Goethite
# Add operon info to DE results
res_operon_24h_G <- res_24h_G %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon_24h_G$operon_id))  # How many DE genes are in operons

operon_summary_24h_G <- res_operon_24h_G %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons_24h_G <- res_operon_24h_G %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))

### Hematite
# Add operon info to DE results
res_operon_24h_H <- res_24h_H %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon_24h_H$operon_id))  # How many DE genes are in operons

operon_summary_24h_H <- res_operon_24h_H %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons_24h_H <- res_operon_24h_H %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))


### Mica
# Add operon info to DE results
res_operon_24h_M <- res_24h_M %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(operon_mapping, by = "ID_prodigal")

table(!is.na(res_operon_24h_M$operon_id))  # How many DE genes are in operons

operon_summary_24h_M <- res_operon_24h_M %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%           # DE genes
  mutate(direction = ifelse(logFC > 0, "up", "down")) %>%
  group_by(operon_id, operon_name, direction) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = direction, values_from = n_DE, values_fill = 0)

# Only DE genes
# Filter DE genes that have operon assigned
de_operons_24h_M <- res_operon_24h_M %>%
  filter(adj.P.Val < 0.05, !is.na(operon_id)) %>%
  group_by(operon_id) %>%
  summarise(n_DE = n(), .groups = "drop") %>%
  arrange(desc(n_DE))
```

```{r test}
name <- "lepA"

operon_summary_3h_G %>%
  filter(grepl(name, operon_name))

operon_summary_24h_G %>%
  filter(grepl(name, operon_name))

operon_summary_3h_H %>%
  filter(grepl(name, operon_name))

operon_summary_24h_H %>%
  filter(grepl(name, operon_name))

operon_summary_3h_M %>%
  filter(grepl(name, operon_name))

operon_summary_24h_M %>%
  filter(grepl(name, operon_name))
```


```{r test2}
# operon_names %>%
#   filter(grepl("lep", operon_name))
# 
# gene_operon_map %>%
#   filter(Parent == "BSGatlas-operon-1431")
# 
# gene_operon_map %>%
#   filter(grepl("cggR", gene_name))

# gene_operon_map %>%
#   filter(ID == "BSGatlas-gene-1048") %>%
#   select(ID, locus_tag, gene_name, start, strand)
```

```{r specific_genes, warning=FALSE, comments="", message=FALSE}

### Goethite 3h
# Prepare table
genes_3h_G <- res_3h_G %>%
  dplyr::select(logFC, adj.P.Val) %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(complete_gene_annotation %>%
  dplyr::select(ID_prodigal, gene, locus_tag), by = "ID_prodigal") %>%
  filter(adj.P.Val < 0.05) %>%
  dplyr::select(ID_prodigal, gene, locus_tag, logFC, adj.P.Val)


### Goethite 24h
# Prepare table
genes_24h_G <- res_24h_G %>%
  dplyr::select(logFC, adj.P.Val) %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(complete_gene_annotation %>%
  dplyr::select(ID_prodigal, gene, locus_tag), by = "ID_prodigal") %>%
  filter(adj.P.Val < 0.05) %>%
  dplyr::select(ID_prodigal, gene, locus_tag, logFC, adj.P.Val)


### Hematite 3h
# Prepare table
genes_3h_H <- res_3h_H %>%
  dplyr::select(logFC, adj.P.Val) %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(complete_gene_annotation %>%
  dplyr::select(ID_prodigal, gene, locus_tag), by = "ID_prodigal") %>%
  filter(adj.P.Val < 0.05) %>%
  dplyr::select(ID_prodigal, gene, locus_tag, logFC, adj.P.Val)


### Hematite 24h
# Prepare table
genes_24h_H <- res_24h_H %>%
  dplyr::select(logFC, adj.P.Val) %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(complete_gene_annotation %>%
  dplyr::select(ID_prodigal, gene, locus_tag), by = "ID_prodigal") %>%
  filter(adj.P.Val < 0.05) %>%
  dplyr::select(ID_prodigal, gene, locus_tag, logFC, adj.P.Val)


### Mica 3h
# Prepare table
genes_3h_M <- res_3h_M %>%
  dplyr::select(logFC, adj.P.Val) %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(complete_gene_annotation %>%
  dplyr::select(ID_prodigal, gene, locus_tag), by = "ID_prodigal") %>%
  filter(adj.P.Val < 0.05) %>%
  dplyr::select(ID_prodigal, gene, locus_tag, logFC, adj.P.Val)



### Mica 24h
# Prepare table
genes_24h_M <- res_24h_M %>%
  dplyr::select(logFC, adj.P.Val) %>%
  rownames_to_column(var = "ID_prodigal") %>%
  left_join(complete_gene_annotation %>%
  dplyr::select(ID_prodigal, gene, locus_tag), by = "ID_prodigal") %>%
  filter(adj.P.Val < 0.05) %>%
  dplyr::select(ID_prodigal, gene, locus_tag, logFC, adj.P.Val)


```

```{r test3}

name <- "yqe"

genes_3h_G %>%
  filter(grepl(name, gene))

genes_24h_G %>%
  filter(grepl(name, gene))

genes_3h_H %>%
  filter(grepl(name, gene))

genes_24h_H %>%
  filter(grepl(name, gene))

genes_3h_M %>%
  filter(grepl(name, gene))

genes_24h_M %>%
  filter(grepl(name, gene))

```



```{r test4}

# top_operon_genes %>%
#   filter(grepl("lepA-hemN-hrcA-etc operon", operon_name))
# 
# prueba_3h_M %>%
#   filter(grepl("NC_000964.3_2632", ID_prodigal))
# 
# prueba_3h_M <- res_3h_M %>%
#   dplyr::select(logFC, adj.P.Val) %>%
#   rownames_to_column(var = "ID_prodigal") %>%
#   left_join(complete_gene_annotation %>%
#   dplyr::select(ID_prodigal, gene, locus_tag), by = "ID_prodigal")
# 
# names_vec <- c("yqeV", "yqeU", "yqeT", "dnaJ", "dnaK", "grpE", "hrcA", "hemN", "lepA")
# 
# pattern <- paste(names_vec, collapse = "|")
# 
# res_3h_M %>%
#   filter(grepl("yqeV", gene))
```





